<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp-firstpass</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnhollowerBaseLib">
      <HintPath>..\Libs\UnhollowerBaseLib.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\Libs\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\Libs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\Libs\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Rewired_Core" />
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\Libs\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\Libs\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\Libs\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\Libs\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.RenderPipelines.HighDefinition.Runtime" />
    <Reference Include="Unity.RenderPipelines.Core.Runtime" />
    <Reference Include="UnityEngine.VideoModule" />
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\Libs\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net" />
    <Reference Include="UnityEngine.VehiclesModule" />
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\Libs\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="Boxophobic.TheVehetationEngine.Runtime" />
    <Reference Include="ZString" />
    <Reference Include="Il2CppSystem" />
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\Libs\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\Libs\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\Libs\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>